import { ColorScheme } from '@contexts/ThemeContext';

export const getCalendarTheme = (colors: ColorScheme) => ({
  backgroundColor: colors.surface,
  calendarBackground: colors.surface,
  textSectionTitleColor: colors.textSecondary,
  selectedDayBackgroundColor: colors.primary,
  selectedDayTextColor: colors.white,
  todayTextColor: colors.primary,
  dayTextColor: colors.textPrimary,
  textDisabledColor: colors.textLight,
  dotColor: colors.primary,
  selectedDotColor: colors.white,
  arrowColor: colors.primary,
  monthTextColor: colors.textPrimary,
  indicatorColor: colors.primary,
  textDayFontFamily: 'System',
  textMonthFontFamily: 'System',
  textDayHeaderFontFamily: 'System',
  textDayFontWeight: '300' as const,
  textMonthFontWeight: '600' as const,
  textDayHeaderFontWeight: '500' as const,
  textDayFontSize: 14,
  textMonthFontSize: 16,
  textDayHeaderFontSize: 12,
});
